-- Author      : Nogarder
-- Create Date : 2013/5/21 16:36:59
NPA.SettingManager.RegisterDefaultProfileFunc("Default",function(profile)
	profile["Default"]= {
		["Number"] = {
			["Timer"] = {
				["ValueType"] = 1,
				["MaxTextData"] = {
					["Width"] = 0,
					["Color"] = {
						["A"] = 1,
						["R"] = 1,
						["G"] = 1,
						["B"] = 1,
					},
					["ColorMode"] = 0,
					["Height"] = 13,
					["ProfileName"] = "Default",
				},
				["ValueTextData"] = {
					["Width"] = 0,
					["Color"] = {
						["A"] = 1,
						["R"] = 1,
						["G"] = 1,
						["B"] = 1,
					},
					["ColorMode"] = 2,
					["Height"] = 11,
					["ProfileName"] = "Default",
				},
				["PercentType"] = 0,
				["MaxType"] = 0,
				["PercentTextData"] = {
					["Width"] = 0,
					["Color"] = {
						["A"] = 1,
						["R"] = 1,
						["G"] = 1,
						["B"] = 1,
					},
					["ColorMode"] = 0,
					["Height"] = 11,
					["ProfileName"] = "Default",
				},
				["MaxColor"] = {
					["A"] = 1,
					["R"] = 0,
					["G"] = 1,
					["B"] = 0,
				},
				["MinColor"] = {
					["A"] = 1,
					["R"] = 1,
					["G"] = 0,
					["B"] = 0,
				},
			},
			["Casting"] = {
				["ValueType"] = 1,
				["MaxTextData"] = {
					["Width"] = 0,
					["Color"] = {
						["A"] = 1,
						["R"] = 1,
						["G"] = 1,
						["B"] = 1,
					},
					["ColorMode"] = 0,
					["Height"] = 11,
					["ProfileName"] = "Default",
				},
				["ValueTextData"] = {
					["Width"] = 0,
					["Color"] = {
						["A"] = 1,
						["R"] = 1,
						["G"] = 1,
						["B"] = 1,
					},
					["ColorMode"] = 0,
					["Height"] = 13,
					["ProfileName"] = "Default",
				},
				["PercentType"] = 0,
				["MaxType"] = 2,
				["PercentTextData"] = {
					["Width"] = 0,
					["Color"] = {
						["A"] = 1,
						["R"] = 1,
						["G"] = 1,
						["B"] = 1,
					},
					["ColorMode"] = 0,
					["Height"] = 11,
					["ProfileName"] = "Default",
				},
				["MaxColor"] = {
					["A"] = 1,
					["R"] = 0,
					["G"] = 1,
					["B"] = 0,
				},
				["MinColor"] = {
					["A"] = 1,
					["R"] = 1,
					["G"] = 0,
					["B"] = 0,
				},
			},
			["Default"] = {
				["ValueType"] = 1,
				["MaxTextData"] = {
					["ProfileName"] = "Default",
					["Height"] = 11,
					["ColorMode"] = 0,
					["Color"] = {
						["A"] = 1,
						["B"] = 1,
						["G"] = 1,
						["R"] = 1,
					},
					["Width"] = 0,
				},
				["PercentType"] = 4,
				["MinColor"] = {
					["A"] = 1,
					["B"] = 0,
					["G"] = 0,
					["R"] = 1,
				},
				["MaxType"] = 1,
				["PercentTextData"] = {
					["ProfileName"] = "Default",
					["Height"] = 11,
					["ColorMode"] = 0,
					["Color"] = {
						["A"] = 1,
						["B"] = 1,
						["G"] = 1,
						["R"] = 1,
					},
					["Width"] = 0,
				},
				["MaxColor"] = {
					["A"] = 1,
					["B"] = 0,
					["G"] = 1,
					["R"] = 0,
				},
				["ValueTextData"] = {
					["ProfileName"] = "Default",
					["Height"] = 11,
					["ColorMode"] = 0,
					["Color"] = {
						["A"] = 1,
						["B"] = 1,
						["G"] = 1,
						["R"] = 1,
					},
					["Width"] = 0,
				},
			},
			["Health"] = {
				["ValueType"] = 2,
				["MaxTextData"] = {
					["Width"] = 0,
					["Color"] = {
						["A"] = 1,
						["R"] = 1,
						["G"] = 1,
						["B"] = 1,
					},
					["ColorMode"] = 0,
					["Height"] = 11,
					["ProfileName"] = "Default",
				},
				["ValueTextData"] = {
					["Width"] = 0,
					["Color"] = {
						["A"] = 1,
						["R"] = 1,
						["G"] = 1,
						["B"] = 1,
					},
					["ColorMode"] = 0,
					["Height"] = 11,
					["ProfileName"] = "Default",
				},
				["PercentType"] = 4,
				["MaxType"] = 0,
				["PercentTextData"] = {
					["Width"] = 0,
					["Color"] = {
						["A"] = 1,
						["R"] = 1,
						["G"] = 1,
						["B"] = 1,
					},
					["ColorMode"] = 0,
					["Height"] = 13,
					["ProfileName"] = "Default",
				},
				["MaxColor"] = {
					["A"] = 1,
					["R"] = 0,
					["G"] = 1,
					["B"] = 0,
				},
				["MinColor"] = {
					["A"] = 1,
					["R"] = 1,
					["G"] = 0,
					["B"] = 0,
				},
			},
		},
		["NamePlate"] = {
			["Default"] = {
				["AlphaSetting"] = {
					{
						["Arg"] = " ",
						["Alpha"] = 1,
						["ConditionType"] = "Default",
					}, -- [1]
				},
				["IconSetting"] = {
					["Class"] = {
						["FrameLevel"] = 1,
						["Scale"] = 1,
						["Layer"] = "BACKGROUND",
						["Alpha"] = 1,
						["Width"] = 20,
						["Height"] = 20,
						["DataType"] = "Class",
						["FrameAnchorData"] = {
							["OffsetX"] = -10,
							["OffsetY"] = 0,
							["To"] = "LEFT",
							["From"] = "RIGHT",
						},
						["AnchorFrame"] = "HealthBarGroup",
					},
					["RaidIcon"] = {
						["FrameLevel"] = 1,
						["Scale"] = 1,
						["Layer"] = "BACKGROUND",
						["Alpha"] = 1,
						["Width"] = 20,
						["Height"] = 20,
						["DataType"] = "RaidTarget",
						["FrameAnchorData"] = {
							["To"] = "TOP",
							["OffsetY"] = 0,
							["OffsetX"] = 0,
							["From"] = "BOTTOM",
						},
						["AnchorFrame"] = "DebuffIconGroup",
					},
					["Casting"] = {
						["FrameLevel"] = 1,
						["Scale"] = 1,
						["Layer"] = "BACKGROUND",
						["Alpha"] = 1,
						["Width"] = 20,
						["Height"] = 20,
						["DataType"] = "Casting",
						["FrameAnchorData"] = {
							["OffsetX"] = -10,
							["OffsetY"] = 0,
							["To"] = "LEFT",
							["From"] = "RIGHT",
						},
						["AnchorFrame"] = "CastingBarGroup",
					},
				},
				["DefaultSetting"] = {
					["LevelText"] = {
						["Anchor"] = "CENTER",
						["Font"] = GameFontNormal:GetFont(),
						["OffsetX"] = -12,
						["AnchorTo"] = "BOTTOMRIGHT",
						["Enable"] = false,
						["OffsetY"] = 10,
						["Height"] = 13,
						["Width"] = 0,
					},
					["HealthBar"] = {
						["Texture"] = "Interface\\TargetingFrame\\UI-TargetingFrame-BarFill",
						["Anchor"] = "BOTTOMLEFT",
						["OffsetX"] = 4,
						["AnchorTo"] = "BOTTOMLEFT",
						["Height"] = 10,
						["OffsetY"] = 5,
						["Enable"] = false,
						["Width"] = 105,
					},
					["SpellIcon"] = {
						["Anchor"] = "CENTER",
						["OffsetX"] = -52,
						["AnchorTo"] = "CENTER",
						["Height"] = 15,
						["OffsetY"] = 10,
						["Enable"] = false,
						["Width"] = 15,
					},
					["NameText"] = {
						["Anchor"] = "BOTTOM",
						["Font"] = GameFontNormal:GetFont(),
						["OffsetX"] = 0,
						["AnchorTo"] = "CENTER",
						["Enable"] = false,
						["OffsetY"] = 0,
						["Height"] = 13,
						["Width"] = 0,
					},
					["BossIcon"] = {
						["Texture"] = "Interface\\TargetingFrame\\UI-TargetingFrame-Skull",
						["Anchor"] = "CENTER",
						["OffsetX"] = -12,
						["AnchorTo"] = "BOTTOMRIGHT",
						["Height"] = 14,
						["OffsetY"] = 10,
						["Enable"] = false,
						["Width"] = 14,
					},
					["EliteIcon"] = {
						["Texture"] = "Interface\\Tooltips\\EliteNameplateicon",
						["Anchor"] = "CENTER",
						["OffsetX"] = -8,
						["AnchorTo"] = "BOTTOMRIGHT",
						["Height"] = 31,
						["OffsetY"] = 9,
						["Enable"] = false,
						["Width"] = 43,
					},
					["ThreatGlow"] = {
						["Texture"] = "Interface\\TargetingFrame\\UI-TargetingFrame-Flash",
						["Anchor"] = "BOTTOMLEFT",
						["OffsetX"] = -8,
						["AnchorTo"] = "BOTTOMLEFT",
						["Height"] = 40,
						["OffsetY"] = -13,
						["Enable"] = false,
						["Width"] = 143,
					},
					["CastBarShield"] = {
						["Texture"] = "Interface\\Tooltips\\Nameplate-CastBar-Shiled",
						["Anchor"] = "CENTER",
						["OffsetX"] = 60,
						["AnchorTo"] = "CENTER",
						["Height"] = 36,
						["OffsetY"] = -36,
						["Enable"] = false,
						["Width"] = 130,
					},
					["Highlight"] = {
						["Texture"] = "",
						["Anchor"] = "TOPLEFT",
						["OffsetX"] = 0,
						["AnchorTo"] = "TOPLEFT",
						["Height"] = 36,
						["OffsetY"] = 0,
						["Enable"] = false,
						["Width"] = 130,
					},
					["CastBarOverlay"] = {
						["Texture"] = "Interface\\Tooltips\\Nameplate-Border",
						["Anchor"] = "CENTER",
						["OffsetX"] = 0,
						["AnchorTo"] = "CENTER",
						["Height"] = 36,
						["OffsetY"] = -18,
						["Enable"] = false,
						["Width"] = 130,
					},
					["RaidIcon"] = {
						["Texture"] = "Interface\\TargetingFrame\\UI-RaidTargetingIcons",
						["Anchor"] = "RIGHT",
						["OffsetX"] = 0,
						["AnchorTo"] = "TOPLEFT",
						["Height"] = 29,
						["OffsetY"] = -18,
						["Enable"] = false,
						["Width"] = 29,
					},
					["CastBar"] = {
						["Texture"] = "Interface\\TargetingFrame\\UI-TargetingFrame-BarFill",
						["Anchor"] = "BOTTOMRIGHT",
						["OffsetX"] = 60,
						["AnchorTo"] = "CENTER",
						["Height"] = 10,
						["OffsetY"] = -5,
						["Enable"] = false,
						["Width"] = 105,
					},
					["Overlay"] = {
						["Texture"] = "Interface\\Tooltips\\Nameplate-Border",
						["Anchor"] = "TOPLEFT",
						["OffsetX"] = 0,
						["AnchorTo"] = "TOPLEFT",
						["Height"] = 36,
						["OffsetY"] = 0,
						["Enable"] = false,
						["Width"] = 130,
					},
				},
				["BarGroupSetting"] = {
					["Health"] = {
						["FrameLevel"] = 1,
						["Scale"] = 1,
						["ColorMode"] = 1,
						["SmoothTime"] = 1,
						["Width"] = 80,
						["AnchorFrame"] = "MainFrame",
						["DataType"] = "Health",
						["Alpha"] = 1,
						["Height"] = 5,
						["ShadowAlpha"] = 0.5,
						["FrameAnchorData"] = {
							["OffsetX"] = 0,
							["OffsetY"] = 0,
							["To"] = "CENTER",
							["From"] = "CENTER",
						},
						["ProfileName"] = "Default",
					},
					["Casting"] = {
						["FrameLevel"] = 1,
						["Scale"] = 1,
						["ColorMode"] = 0,
						["SmoothTime"] = 1,
						["Width"] = 80,
						["AnchorFrame"] = "HealthNumber",
						["DataType"] = "Casting",
						["Alpha"] = 1,
						["Height"] = 3,
						["ShadowAlpha"] = 0.5,
						["FrameAnchorData"] = {
							["OffsetX"] = 0,
							["OffsetY"] = -5,
							["To"] = "BOTTOM",
							["From"] = "TOP",
						},
						["ProfileName"] = "Default",
					},
				},
				["NumberSetting"] = {
					["Casting"] = {
						["AnchorFrame"] = "CastingBarGroup",
						["FrameAnchorData"] = {
							["OffsetX"] = 0,
							["OffsetY"] = 0,
							["To"] = "CENTER",
							["From"] = "CENTER",
						},
						["FrameLevel"] = 6,
						["ProfileName"] = "Casting",
						["Scale"] = 1,
						["ColorMode"] = 5,
						["Alpha"] = 1,
						["DataType"] = "Casting",
					},
					["Quest"] = {
						["AnchorFrame"] = "HealthBarGroup",
						["FrameAnchorData"] = {
							["OffsetX"] = 5,
							["OffsetY"] = 0,
							["To"] = "BOTTOMRIGHT",
							["From"] = "TOPLEFT",
						},
						["FrameLevel"] = 1,
						["ProfileName"] = "Casting",
						["Scale"] = 1,
						["ColorMode"] = 0,
						["Alpha"] = 1,
						["DataType"] = "Quest",
					},
					["Health"] = {
						["AnchorFrame"] = "HealthBarGroup",
						["FrameAnchorData"] = {
							["OffsetX"] = 0,
							["OffsetY"] = -3,
							["To"] = "CENTER",
							["From"] = "CENTER",
						},
						["FrameLevel"] = 2,
						["ProfileName"] = "Health",
						["Scale"] = 1,
						["ColorMode"] = 2,
						["Alpha"] = 1,
						["DataType"] = "Health",
					},
				},
				["IconGroupSetting"] = {
					["Debuff"] = {
						["PerRow"] = 6,
						["Direction"] = 1,
						["FrameLevel"] = 1,
						["GapX"] = 2,
						["Scale"] = 1,
						["Alpha"] = 1,
						["DataType"] = "Aura",
						["GapY"] = 2,
						["DataRules"] = {
							["Debuff"] = {
								["FrameLevel"] = 1,
								["Scale"] = 1,
								["Alpha"] = 1,
								["FilterType"] = 2,
								["Modules"] = {
									["Icon"] = {
										["ModuleType"] = "Icon",
										["Scale"] = 1,
										["ColorMode"] = 0,
										["Alpha"] = 1,
										["DataType"] = "Stack",
										["Width"] = 20,
										["Height"] = 20,
										["AnchorData"] = {
											["OffsetX"] = 0,
											["OffsetY"] = 0,
											["To"] = "CENTER",
											["From"] = "CENTER",
										},
										["FrameLevel"] = 1,
										["ProfileName"] = " ",
									},
									["Text"] = {
										["ModuleType"] = "Number",
										["Scale"] = 1,
										["ColorMode"] = 0,
										["Alpha"] = 1,
										["DataType"] = "Time",
										["Width"] = 10,
										["Height"] = 10,
										["AnchorData"] = {
											["OffsetX"] = 0,
											["OffsetY"] = 0,
											["To"] = "BOTTOM",
											["From"] = "BOTTOM",
										},
										["FrameLevel"] = 10,
										["ProfileName"] = "Timer",
									},
								},
								["SpellList"] = {
								},
								["SchoolList"] = {
									["Enrage"] = true,
									["Bleed"] = true,
									["Curse"] = true,
									["Poison"] = true,
									["Magic"] = true,
									["None"] = true,
								},
								["Height"] = 20,
								["Priority"] = 1,
								["Width"] = 20,
								["FromType"] = 2,
							},
						},
						["TimeLimit"] = 60,
						["Max"] = 12,
						["FrameAnchorData"] = {
							["OffsetX"] = 0,
							["OffsetY"] = 5,
							["To"] = "TOP",
							["From"] = "BOTTOM",
						},
						["AnchorFrame"] = "NameText",
					},
				},
				["TextSetting"] = {
					["Level"] = {
						["FrameLevel"] = 1,
						["Color"] = {
							["A"] = 1,
							["B"] = 1,
							["G"] = 1,
							["R"] = 1,
						},
						["Layer"] = "BACKGROUND",
						["Alpha"] = 1,
						["Width"] = 0,
						["AnchorFrame"] = "HealthBarGroup",
						["DataType"] = "Level",
						["Scale"] = 1.22,
						["Height"] = 11,
						["ColorMode"] = 4,
						["FrameAnchorData"] = {
							["OffsetX"] = 5,
							["OffsetY"] = 0,
							["To"] = "RIGHT",
							["From"] = "LEFT",
						},
						["ProfileName"] = "Default",
					},
					["SpellLock"] = {
						["FrameLevel"] = 1,
						["Color"] = {
							["A"] = 1,
							["B"] = 1,
							["G"] = 1,
							["R"] = 1,
						},
						["Layer"] = "BACKGROUND",
						["Alpha"] = 1,
						["Width"] = 0,
						["AnchorFrame"] = "HealthBarGroup",
						["DataType"] = "SpellLock",
						["Scale"] = 1,
						["Height"] = 11,
						["ColorMode"] = 0,
						["FrameAnchorData"] = {
							["OffsetX"] = 0,
							["OffsetY"] = -35,
							["To"] = "BOTTOM",
							["From"] = "TOP",
						},
						["ProfileName"] = "Default",
					},
					["Name"] = {
						["FrameLevel"] = 1,
						["Color"] = {
							["A"] = 1,
							["B"] = 1,
							["G"] = 1,
							["R"] = 1,
						},
						["Layer"] = "BACKGROUND",
						["Alpha"] = 1,
						["Width"] = 0,
						["AnchorFrame"] = "HealthBarGroup",
						["DataType"] = "Name",
						["Scale"] = 1,
						["Height"] = 11,
						["ColorMode"] = 0,
						["FrameAnchorData"] = {
							["OffsetX"] = 0,
							["OffsetY"] = 0,
							["To"] = "TOP",
							["From"] = "BOTTOM",
						},
						["ProfileName"] = "Default",
					},
					["Casting"] = {
						["FrameLevel"] = 1,
						["Color"] = {
							["A"] = 1,
							["B"] = 1,
							["G"] = 1,
							["R"] = 1,
						},
						["Layer"] = "BACKGROUND",
						["Alpha"] = 1,
						["Width"] = 0,
						["AnchorFrame"] = "CastingBarGroup",
						["DataType"] = "Casting",
						["Scale"] = 1,
						["Height"] = 11,
						["ColorMode"] = 5,
						["FrameAnchorData"] = {
							["OffsetX"] = 0,
							["OffsetY"] = -12,
							["To"] = "CENTER",
							["From"] = "CENTER",
						},
						["ProfileName"] = "Default",
					},
				},
				["TextureGroupSetting"] = {
					["Casting"] = {
						["FrameLevel"] = 0,
						["Scale"] = 1,
						["Alpha"] = 0.4,
						["DataType"] = "Casting",
						["TextureGroup"] = {
							["1"] = {
								["ProfileName"] = "Default",
								["AnchorData"] = {
									["OffsetX"] = 0,
									["OffsetY"] = 0,
									["To"] = "CENTER",
									["From"] = "CENTER",
								},
								["Layer"] = "BACKGROUND",
								["Height"] = 4,
								["Width"] = 80,
							},
						},
						["Height"] = 6,
						["Width"] = 80,
						["FrameAnchorData"] = {
							["OffsetX"] = 0,
							["OffsetY"] = 0,
							["To"] = "CENTER",
							["From"] = "CENTER",
						},
						["AnchorFrame"] = "CastingBarGroup",
					},
					["Healthbar"] = {
						["FrameLevel"] = 0,
						["Scale"] = 1,
						["Alpha"] = 0.4,
						["DataType"] = "None",
						["TextureGroup"] = {
							["1"] = {
								["ProfileName"] = "Default",
								["AnchorData"] = {
									["OffsetX"] = 0,
									["OffsetY"] = 0,
									["To"] = "CENTER",
									["From"] = "CENTER",
								},
								["Layer"] = "BACKGROUND",
								["Height"] = 6,
								["Width"] = 80,
							},
						},
						["Height"] = 20,
						["Width"] = 80,
						["FrameAnchorData"] = {
							["OffsetX"] = 0,
							["OffsetY"] = 0,
							["To"] = "CENTER",
							["From"] = "CENTER",
						},
						["AnchorFrame"] = "MainFrame",
					},
					["CasingShield"] = {
						["FrameLevel"] = 0,
						["Scale"] = 1,
						["Alpha"] = 1,
						["DataType"] = "CastingShield",
						["TextureGroup"] = {
							["1"] = {
								["ProfileName"] = "Shield",
								["AnchorData"] = {
									["OffsetX"] = 0,
									["OffsetY"] = 0,
									["To"] = "CENTER",
									["From"] = "CENTER",
								},
								["Layer"] = "BACKGROUND",
								["Height"] = 15,
								["Width"] = 86,
							},
						},
						["Height"] = 20,
						["Width"] = 20,
						["FrameAnchorData"] = {
							["OffsetX"] = 0,
							["OffsetY"] = 0,
							["To"] = "CENTER",
							["From"] = "CENTER",
						},
						["AnchorFrame"] = "CastingBarGroup",
					},
				},
			},
		},
		["SpellLib"] = {},
		["Color"] = {
			["SpellType"] = {
				["Enrage"] = {
					["A"] = 1,
					["B"] = 0,
					["G"] = 0,
					["R"] = 1,
				},
				["Disease"] = {
					["A"] = 1,
					["B"] = 0,
					["G"] = 0.6,
					["R"] = 0.6,
				},
				["Bleed"] = {
					["A"] = 1,
					["B"] = 0,
					["G"] = 1,
					["R"] = 1,
				},
				["Poison"] = {
					["A"] = 1,
					["B"] = 0,
					["G"] = 1,
					["R"] = 0,
				},
				["Curse"] = {
					["A"] = 1,
					["B"] = 1,
					["G"] = 0,
					["R"] = 1,
				},
				["Magic"] = {
					["A"] = 1,
					["B"] = 1,
					["G"] = 0,
					["R"] = 0,
				},
				["None"] = {
					["A"] = 1,
					["B"] = 1,
					["G"] = 1,
					["R"] = 1,
				},
			},
			["Threat"] = {
				{
					["A"] = 1,
					["B"] = 0.466665655374527,
					["G"] = 0.9999977946281433,
					["R"] = 0.9999977946281433,
				}, -- [1]
				{
					["A"] = 1,
					["B"] = 0,
					["G"] = 0.5999986529350281,
					["R"] = 0.9999977946281433,
				}, -- [2]
				{
					["A"] = 1,
					["B"] = 0,
					["G"] = 0,
					["R"] = 0.9999977946281433,
				}, -- [3]
				{
					["A"] = 1,
					["B"] = 1,
					["G"] = 1,
					["R"] = 1,
				}, -- [4]
				[0] = {
					["A"] = 1,
					["B"] = 0.6901945471763611,
					["G"] = 0.6901945471763611,
					["R"] = 0.6901945471763611,
				},
			},
			["SpellSchool"] = {
				{
					["A"] = 1,
					["B"] = 0,
					["G"] = 1,
					["R"] = 1,
				}, -- [1]
				{
					["A"] = 1,
					["B"] = 0.5,
					["G"] = 1,
					["R"] = 1,
				}, -- [2]
				nil, -- [3]
				{
					["A"] = 1,
					["B"] = 0,
					["G"] = 0.3,
					["R"] = 1,
				}, -- [4]
				[8] = {
					["A"] = 1,
					["B"] = 0.25,
					["G"] = 1,
					["R"] = 0.25,
				},
				[16] = {
					["A"] = 1,
					["B"] = 1,
					["G"] = 1,
					["R"] = 0.5,
				},
				[32] = {
					["A"] = 1,
					["B"] = 1,
					["G"] = 0.5,
					["R"] = 0.5,
				},
				[64] = {
					["A"] = 1,
					["B"] = 1,
					["g"] = 0.5,
					["R"] = 1,
				},
			},
			["Faction"] = {
				{
					["A"] = 1,
					["B"] = 0,
					["G"] = 1,
					["R"] = 0,
				}, -- [1]
				{
					["A"] = 1,
					["B"] = 0,
					["G"] = 1,
					["R"] = 1,
				}, -- [2]
				{
					["A"] = 1,
					["B"] = 0,
					["G"] = 0,
					["R"] = 1,
				}, -- [3]
			},
		},
		["Class"] = {
			["HUNTER"] = {
				["Color"] = {
					["A"] = 1,
					["B"] = 0.45,
					["G"] = 0.83,
					["R"] = 0.67,
				},
				["ProfileName"] = "PlayerClassIcon_HUNTER",
			},
			["WARRIOR"] = {
				["Color"] = {
					["A"] = 1,
					["B"] = 0.43,
					["G"] = 0.61,
					["R"] = 0.78,
				},
				["ProfileName"] = "PlayerClassIcon_WARRIOR",
			},
			["SHAMAN"] = {
				["Color"] = {
					["A"] = 1,
					["B"] = 0.87,
					["G"] = 0.44,
					["R"] = 0,
				},
				["ProfileName"] = "PlayerClassIcon_SHAMAN",
			},
			["MAGE"] = {
				["Color"] = {
					["A"] = 1,
					["B"] = 0.94,
					["G"] = 0.8,
					["R"] = 0.41,
				},
				["ProfileName"] = "PlayerClassIcon_MAGE",
			},
			["PRIEST"] = {
				["Color"] = {
					["A"] = 1,
					["B"] = 1,
					["G"] = 1,
					["R"] = 1,
				},
				["ProfileName"] = "PlayerClassIcon_PRIEST",
			},
			["WARLOCK"] = {
				["Color"] = {
					["A"] = 1,
					["B"] = 0.79,
					["G"] = 0.51,
					["R"] = 0.58,
				},
				["ProfileName"] = "PlayerClassIcon_WARLOCK",
			},
			["ROGUE"] = {
				["Color"] = {
					["A"] = 1,
					["B"] = 0.41,
					["G"] = 0.96,
					["R"] = 1,
				},
				["ProfileName"] = "PlayerClassIcon_ROGUE",
			},
			["DEATHKNIGHT"] = {
				["Color"] = {
					["A"] = 1,
					["B"] = 0.23,
					["G"] = 0.12,
					["R"] = 0.77,
				},
				["ProfileName"] = "PlayerClassIcon_DEATHKNIGHT",
			},
			["DRUID"] = {
				["Color"] = {
					["A"] = 1,
					["B"] = 0.04,
					["G"] = 0.49,
					["R"] = 1,
				},
				["ProfileName"] = "PlayerClassIcon_DRUID",
			},
			["MONK"] = {
				["Color"] = {
					["A"] = 1,
					["B"] = 0.59,
					["G"] = 1,
					["R"] = 0,
				},
				["ProfileName"] = "PlayerClassIcon_MONK",
			},
			["PALADIN"] = {
				["Color"] = {
					["A"] = 1,
					["B"] = 0.73,
					["G"] = 0.55,
					["R"] = 0.96,
				},
				["ProfileName"] = "PlayerClassIcon_PALADIN",
			},
		},
		["BarGroup"] = {
			["Default"] = {
				["1"] = {
					["Direction"] = 0,
					["PercentFrom"] = 0,
					["EnableTextureChange"] = false,
					["Layer"] = "ARTWORK",
					["PercentTo"] = 1,
					["Width"] = 140,
					["MinColor"] = {
						["A"] = 1,
						["B"] = 1,
						["G"] = 1,
						["R"] = 1,
					},
					["HideWhenMax"] = false,
					["Height"] = 20,
					["MaxColor"] = {
						["A"] = 1,
						["B"] = 1,
						["G"] = 1,
						["R"] = 1,
					},
					["AnchorData"] = {
						["OffsetX"] = -70,
						["OffsetY"] = 0,
						["To"] = "CENTER",
						["From"] = "LEFT",
					},
					["EnableSizeChange"] = true,
					["ColorMode"] = 0,
					["ProfileName"] = "Default",
				},
			},
		},
		["TargetArrow"] = {
			["1"] = {
				["FrameLevel"] = 1,
				["To"] = 0,
				["StartOffsetY"] = 0,
				["StartOffsetX"] = 0,
				["SpeedPerSecond"] = 1,
				["Alpha"] = 1,
				["EndOffsetX"] = 0,
				["StartSize"] = 5,
				["MaxPerLine"] = 10,
				["Gap"] = 30,
				["EndOffsetY"] = 0,
				["TextureFileName"] = "Arrow",
				["From"] = 4,
				["EndSize"] = 28,
				["Color"] = {
					["A"] = 1,
					["R"] = 0,
					["G"] = 1,
					["B"] = 0,
				},
			},
			["2"] = {
				["FrameLevel"] = 1,
				["To"] = 0,
				["StartOffsetY"] = 0,
				["StartOffsetX"] = 0,
				["SpeedPerSecond"] = 1,
				["Alpha"] = 1,
				["EndOffsetX"] = 0,
				["StartSize"] = 5,
				["MaxPerLine"] = 10,
				["Gap"] = 30,
				["EndOffsetY"] = 0,
				["TextureFileName"] = "Arrow",
				["From"] = 5,
				["EndSize"] = 19,
				["Color"] = {
					["A"] = 1,
					["R"] = 1,
					["G"] = 0,
					["B"] = 0,
				},
			},
		},
		["Core"] = {
			["DataCollectors"] = {
				["RaidTarget"] = true,
				["Threat"] = true,
				["Classification"] = true,
				["Casting"] = true,
				["UnitID"] = true,
				["Level"] = true,
				["Alpha"] = true,
				["Summoned"] = true,
				["Type"] = true,
				["Name"] = true,
				["Health"] = true,
				["Aura"] = true,
				["Target"] = true,
				["SpellLock"] = true,
				["Quest"] = true,
				["CoolDown"] = true,
			},
			["NamePlateModules"] = {
				["Number"] = true,
				["TextureGroup"] = true,
				["Default"] = true,
				["IconGroup"] = true,
				["Icon"] = true,
				["Text"] = true,
				["BarGroup"] = true,
				["MainFrame"] = true,
			},
		},
		["Font"] = {
			["Default"] = {
				["Font"] = GameFontNormal:GetFont(),
				["ShadowX"] = 1,
				["ShadowY"] = -1,
				["Mode"] = "OUTLINE",
				["Color"] = {
					["A"] = 1,
					["B"] = 1,
					["G"] = 1,
					["R"] = 1,
				},
			},
		},
		["CombatText"] = {
			["Condition"] = {
				["Interrupt"] = {
					["BGColor"] = {
						["A"] = 1,
						["R"] = 1,
						["G"] = 1,
						["B"] = 1,
					},
					["CritType"] = 0,
					["To"] = 0,
					["TextFileName"] = "Default",
					["BGFileName"] = "Empty",
					["BGHeight"] = 10,
					["TextWidth"] = 0,
					["SpellListType"] = 0,
					["SpellList"] = {
					},
					["AnimationName"] = "2",
					["From"] = 0,
					["EventList"] = {
						["SPELL_AURA_APPLIED_DOSE"] = false,
						["SPELL_MISSED"] = false,
						["SPELL_STOLEN"] = false,
						["RANGE_EXTRA_ATTACKS"] = false,
						["SPELL_INTERRUPT"] = true,
						["SPELL_SUMMON"] = false,
						["SWING_MISSED"] = false,
						["UNIT_DESTROYED"] = false,
						["SPELL_RESURRECT"] = false,
						["SPELL_ENERGIZE"] = false,
						["ENVIRONMENTAL_DAMAGE"] = false,
						["SPELL_LEECH"] = false,
						["SPELL_AURA_BROKEN"] = false,
						["UNIT_DIED"] = false,
						["SPELL_HEAL"] = false,
						["SPELL_PERIODIC_HEAL"] = false,
						["SPELL_AURA_REMOVED_DOSE"] = false,
						["SPELL_DISPEL_FAILED"] = false,
						["SWING_EXTRA_ATTACKS"] = false,
						["SPELL_PERIODIC_DAMAGE"] = false,
						["SPELL_DAMAGE"] = false,
						["SWING_DAMAGE"] = false,
						["SPELL_AURA_BROKEN_SPELL"] = false,
						["SPELL_CREATE"] = false,
						["RANGE_MISSED"] = false,
						["RANGE_DAMAGE"] = false,
						["SPELL_AURA_APPLIED"] = false,
						["SPELL_AURA_REMOVED"] = false,
						["SPELL_DISPEL"] = false,
						["SPELL_DRAIN"] = false,
					},
					["IconSize"] = 20,
					["BGWidth"] = 10,
					["TextType"] = 2,
					["TextHeight"] = 19,
				},
				["Normal"] = {
					["BGColor"] = {
						["A"] = 1,
						["R"] = 1,
						["G"] = 1,
						["B"] = 1,
					},
					["TextFileName"] = "Default",
					["To"] = 0,
					["CritType"] = 2,
					["BGFileName"] = "Empty",
					["BGHeight"] = 10,
					["TextWidth"] = 0,
					["SpellListType"] = 0,
					["SpellList"] = {
					},
					["AnimationName"] = "1",
					["From"] = 1,
					["EventList"] = {
						["SPELL_AURA_APPLIED_DOSE"] = true,
						["SPELL_MISSED"] = true,
						["SPELL_SUMMON"] = true,
						["RANGE_EXTRA_ATTACKS"] = true,
						["SPELL_AURA_REMOVED"] = true,
						["SPELL_INTERRUPT"] = false,
						["SWING_MISSED"] = true,
						["UNIT_DESTROYED"] = true,
						["SPELL_RESURRECT"] = true,
						["SPELL_STOLEN"] = true,
						["ENVIRONMENTAL_DAMAGE"] = true,
						["SPELL_LEECH"] = true,
						["SPELL_AURA_BROKEN"] = true,
						["UNIT_DIED"] = true,
						["SPELL_HEAL"] = true,
						["SPELL_PERIODIC_HEAL"] = true,
						["SPELL_AURA_REMOVED_DOSE"] = true,
						["SPELL_DISPEL_FAILED"] = true,
						["SWING_EXTRA_ATTACKS"] = true,
						["SPELL_PERIODIC_DAMAGE"] = true,
						["SPELL_DAMAGE"] = true,
						["SWING_DAMAGE"] = true,
						["SPELL_AURA_BROKEN_SPELL"] = true,
						["SPELL_CREATE"] = true,
						["RANGE_MISSED"] = true,
						["RANGE_DAMAGE"] = true,
						["SPELL_AURA_APPLIED"] = true,
						["SPELL_ENERGIZE"] = true,
						["SPELL_DISPEL"] = true,
						["SPELL_DRAIN"] = true,
					},
					["IconSize"] = 20,
					["BGWidth"] = 10,
					["TextType"] = 2,
					["TextHeight"] = 12,
				},
				["Critical"] = {
					["BGColor"] = {
						["A"] = 1,
						["R"] = 1,
						["G"] = 1,
						["B"] = 1,
					},
					["TextFileName"] = "Default",
					["To"] = 0,
					["TextHeight"] = 19,
					["BGFileName"] = "Empty",
					["TextWidth"] = 0,
					["BGHeight"] = 10,
					["SpellListType"] = 0,
					["SpellList"] = {
					},
					["AnimationName"] = "2",
					["From"] = 1,
					["EventList"] = {
						["SPELL_AURA_APPLIED_DOSE"] = true,
						["SPELL_MISSED"] = true,
						["SPELL_STOLEN"] = true,
						["RANGE_EXTRA_ATTACKS"] = true,
						["SPELL_INTERRUPT"] = true,
						["SPELL_SUMMON"] = true,
						["SWING_MISSED"] = true,
						["UNIT_DESTROYED"] = true,
						["SPELL_RESURRECT"] = true,
						["SPELL_ENERGIZE"] = true,
						["ENVIRONMENTAL_DAMAGE"] = true,
						["SPELL_LEECH"] = true,
						["SPELL_AURA_BROKEN"] = true,
						["UNIT_DIED"] = true,
						["SPELL_HEAL"] = true,
						["SPELL_PERIODIC_HEAL"] = true,
						["SPELL_AURA_REMOVED_DOSE"] = true,
						["SPELL_DISPEL_FAILED"] = true,
						["SWING_EXTRA_ATTACKS"] = true,
						["SPELL_PERIODIC_DAMAGE"] = true,
						["SPELL_DAMAGE"] = true,
						["SWING_DAMAGE"] = true,
						["SPELL_AURA_BROKEN_SPELL"] = true,
						["SPELL_CREATE"] = true,
						["RANGE_MISSED"] = true,
						["RANGE_DAMAGE"] = true,
						["SPELL_AURA_APPLIED"] = true,
						["SPELL_AURA_REMOVED"] = true,
						["SPELL_DISPEL"] = true,
						["SPELL_DRAIN"] = true,
					},
					["IconSize"] = 20,
					["BGWidth"] = 10,
					["TextType"] = 2,
					["CritType"] = 1,
				},
			},
			["Animation"] = {
				["1"] = {
					{
						["StartAlpha"] = 0.5,
						["ShakeRange"] = 0,
						["Lasts"] = 0.2,
						["SpeedType"] = 5,
						["AccType"] = 2,
						["StartSize"] = 0.5,
						["FrameLevel"] = 1,
						["EndAlpha"] = 1,
						["SpeedY"] = 148,
						["AccX"] = 0,
						["AccY"] = 100,
						["EndSize"] = 1,
						["SpeedX"] = 500,
					}, -- [1]
					{
						["StartAlpha"] = 1,
						["SpeedX"] = 0,
						["FrameLevel"] = 1,
						["SpeedType"] = 0,
						["AccType"] = 0,
						["StartSize"] = 1,
						["ShakeRange"] = 0,
						["EndAlpha"] = 0.2,
						["AccX"] = 0,
						["SpeedY"] = 25,
						["AccY"] = 0,
						["EndSize"] = 1,
						["Lasts"] = 0.8,
					}, -- [2]
				},
				["2"] = {
					{
						["StartAlpha"] = 0.5,
						["SpeedX"] = 800,
						["FrameLevel"] = 1,
						["SpeedType"] = 5,
						["AccType"] = 2,
						["StartSize"] = 0.5,
						["Lasts"] = 0.2,
						["EndAlpha"] = 1,
						["SpeedY"] = 300,
						["AccX"] = 0,
						["AccY"] = 100,
						["EndSize"] = 1,
						["ShakeRange"] = 0,
					}, -- [1]
					{
						["StartAlpha"] = 1,
						["ShakeRange"] = 2,
						["Lasts"] = 0.8,
						["SpeedType"] = 0,
						["AccType"] = 0,
						["StartSize"] = 1,
						["SpeedX"] = 0,
						["EndAlpha"] = 0.2,
						["AccX"] = 0,
						["SpeedY"] = 25,
						["AccY"] = 0,
						["EndSize"] = 1,
						["FrameLevel"] = 1,
					}, -- [2]
				},
			},
		},
		["NamePlateCondition"] = {
			{
				["Profile"] = "Default",
				["Arg"] = "",
				["ConditionType"] = "Any",
			}, -- [1]
		},
		["RaidTarget"] = {
			["1"] = "RaidTarget1_YellowStar",
			["8"] = "RaidTarget8_WhiteSkull",
			["3"] = "RaidTarget3_PurpleDiamond",
			["2"] = "RaidTarget2_OrangeCircle",
			["5"] = "RaidTarget5_SilverMoon",
			["4"] = "RaidTarget4_GreenTriangle",
			["7"] = "RaidTarget7_RedCross",
			["6"] = "RaidTarget6_BlueSquare",
		},
		["Texture"] = {
			["PlayerClassIcon_SHAMAN"] = {
				["Top"] = 0.25,
				["RAngle"] = 0,
				["Mode"] = "BLEND",
				["Bottom"] = 0.5,
				["Color"] = {
					["A"] = 1,
					["R"] = 1,
					["G"] = 1,
					["B"] = 1,
				},
				["Right"] = 0.49609375,
				["Left"] = 0.25,
				["Texture"] = "Interface\\Glues\\CharacterCreate\\UI-CharacterCreate-Classes",
			},
			["Arrow"] = {
				["Top"] = 0,
				["RAngle"] = 0,
				["Right"] = 1,
				["Bottom"] = 1,
				["Color"] = {
					["A"] = 1,
					["R"] = 1,
					["G"] = 1,
					["B"] = 1,
				},
				["Mode"] = "BLEND",
				["Left"] = 0,
				["Texture"] = "Interface\\Addons\\NPA2\\texture\\arrow",
			},
			["Shield"] = {
				["Top"] = 0,
				["RAngle"] = 0,
				["Right"] = 1,
				["Bottom"] = 1,
				["Color"] = {
					["A"] = 1,
					["R"] = 1,
					["G"] = 1,
					["B"] = 1,
				},
				["Mode"] = "BLEND",
				["Left"] = 0,
				["Texture"] = "Interface\\Tooltips\\UI-StatusBar-Border",
			},
			["PlayerClassIcon_WARRIOR"] = {
				["Top"] = 0,
				["RAngle"] = 0,
				["Mode"] = "BLEND",
				["Bottom"] = 0.25,
				["Color"] = {
					["A"] = 1,
					["R"] = 1,
					["G"] = 1,
					["B"] = 1,
				},
				["Right"] = 0.25,
				["Left"] = 0,
				["Texture"] = "Interface\\Glues\\CharacterCreate\\UI-CharacterCreate-Classes",
			},
			["RaidTarget8_WhiteSkull"] = {
				["Top"] = 0.25,
				["RAngle"] = 0,
				["Mode"] = "Blend",
				["Bottom"] = 0.5,
				["Color"] = {
					["A"] = 1,
					["R"] = 1,
					["G"] = 1,
					["B"] = 1,
				},
				["Right"] = 1,
				["Left"] = 0.75,
				["Texture"] = "Interface\\TargetingFrame\\UI-RaidTargetingIcons",
			},
			["PlayerClassIcon_MAGE"] = {
				["Top"] = 0,
				["RAngle"] = 0,
				["Mode"] = "BLEND",
				["Bottom"] = 0.25,
				["Color"] = {
					["A"] = 1,
					["R"] = 1,
					["G"] = 1,
					["B"] = 1,
				},
				["Right"] = 0.49609375,
				["Left"] = 0.25,
				["Texture"] = "Interface\\Glues\\CharacterCreate\\UI-CharacterCreate-Classes",
			},
			["RaidTarget6_BlueSquare"] = {
				["Top"] = 0.25,
				["RAngle"] = 0,
				["Mode"] = "Blend",
				["Bottom"] = 0.5,
				["Color"] = {
					["A"] = 1,
					["R"] = 1,
					["G"] = 1,
					["B"] = 1,
				},
				["Right"] = 0.5,
				["Left"] = 0.25,
				["Texture"] = "Interface\\TargetingFrame\\UI-RaidTargetingIcons",
			},
			["PlayerClassIcon_PALADIN"] = {
				["Top"] = 0.5,
				["RAngle"] = 0,
				["Mode"] = "BLEND",
				["Bottom"] = 0.75,
				["Color"] = {
					["A"] = 1,
					["R"] = 1,
					["G"] = 1,
					["B"] = 1,
				},
				["Right"] = 0.25,
				["Left"] = 0,
				["Texture"] = "Interface\\Glues\\CharacterCreate\\UI-CharacterCreate-Classes",
			},
			["RaidTarget7_RedCross"] = {
				["Top"] = 0.25,
				["RAngle"] = 0,
				["Mode"] = "Blend",
				["Bottom"] = 0.5,
				["Color"] = {
					["A"] = 1,
					["R"] = 1,
					["G"] = 1,
					["B"] = 1,
				},
				["Right"] = 0.75,
				["Left"] = 0.5,
				["Texture"] = "Interface\\TargetingFrame\\UI-RaidTargetingIcons",
			},
			["PlayerClassIcon_PRIEST"] = {
				["Top"] = 0.25,
				["RAngle"] = 0,
				["Mode"] = "BLEND",
				["Bottom"] = 0.5,
				["Color"] = {
					["A"] = 1,
					["R"] = 1,
					["G"] = 1,
					["B"] = 1,
				},
				["Right"] = 0.7421875,
				["Left"] = 0.49609375,
				["Texture"] = "Interface\\Glues\\CharacterCreate\\UI-CharacterCreate-Classes",
			},
			["RaidTarget3_PurpleDiamond"] = {
				["Top"] = 0,
				["RAngle"] = 0,
				["Mode"] = "Blend",
				["Bottom"] = 0.25,
				["Color"] = {
					["A"] = 1,
					["R"] = 1,
					["G"] = 1,
					["B"] = 1,
				},
				["Right"] = 0.75,
				["Left"] = 0.5,
				["Texture"] = "Interface\\TargetingFrame\\UI-RaidTargetingIcons",
			},
			["RaidTarget5_SilverMoon"] = {
				["Top"] = 0.25,
				["RAngle"] = 0,
				["Mode"] = "Blend",
				["Bottom"] = 0.5,
				["Color"] = {
					["A"] = 1,
					["R"] = 1,
					["G"] = 1,
					["B"] = 1,
				},
				["Right"] = 0.25,
				["Left"] = 0,
				["Texture"] = "Interface\\TargetingFrame\\UI-RaidTargetingIcons",
			},
			["Empty"] = {
				["Top"] = 0,
				["RAngle"] = 0,
				["Right"] = 1,
				["Bottom"] = 1,
				["Color"] = {
					["A"] = 1,
					["R"] = 1,
					["G"] = 1,
					["B"] = 1,
				},
				["Mode"] = "BLEND",
				["Left"] = 0,
				["Texture"] = "",
			},
			["PlayerClassIcon_DEATHKNIGHT"] = {
				["Top"] = 0.5,
				["RAngle"] = 0,
				["Mode"] = "BLEND",
				["Bottom"] = 0.75,
				["Color"] = {
					["A"] = 1,
					["R"] = 1,
					["G"] = 1,
					["B"] = 1,
				},
				["Right"] = 0.5,
				["Left"] = 0.25,
				["Texture"] = "Interface\\Glues\\CharacterCreate\\UI-CharacterCreate-Classes",
			},
			["RaidTarget2_OrangeCircle"] = {
				["Top"] = 0,
				["RAngle"] = 0,
				["Mode"] = "Blend",
				["Bottom"] = 0.25,
				["Color"] = {
					["A"] = 1,
					["R"] = 1,
					["G"] = 1,
					["B"] = 1,
				},
				["Right"] = 0.5,
				["Left"] = 0.25,
				["Texture"] = "Interface\\TargetingFrame\\UI-RaidTargetingIcons",
			},
			["PlayerClassIcon_ROGUE"] = {
				["Top"] = 0,
				["RAngle"] = 0,
				["Mode"] = "BLEND",
				["Bottom"] = 0.25,
				["Color"] = {
					["A"] = 1,
					["R"] = 1,
					["G"] = 1,
					["B"] = 1,
				},
				["Right"] = 0.7421875,
				["Left"] = 0.49609375,
				["Texture"] = "Interface\\Glues\\CharacterCreate\\UI-CharacterCreate-Classes",
			},
			["RaidTarget1_YellowStar"] = {
				["Top"] = 0,
				["RAngle"] = 0,
				["Mode"] = "Blend",
				["Bottom"] = 0.25,
				["Color"] = {
					["A"] = 1,
					["R"] = 1,
					["G"] = 1,
					["B"] = 1,
				},
				["Right"] = 0.25,
				["Left"] = 0,
				["Texture"] = "Interface\\TargetingFrame\\UI-RaidTargetingIcons",
			},
			["PlayerClassIcon_HUNTER"] = {
				["Top"] = 0.25,
				["RAngle"] = 0,
				["Mode"] = "BLEND",
				["Bottom"] = 0.5,
				["Color"] = {
					["A"] = 1,
					["R"] = 1,
					["G"] = 1,
					["B"] = 1,
				},
				["Right"] = 0.25,
				["Left"] = 0,
				["Texture"] = "Interface\\Glues\\CharacterCreate\\UI-CharacterCreate-Classes",
			},
			["PlayerClassIcon_MONK"] = {
				["Top"] = 0.5,
				["RAngle"] = 0,
				["Mode"] = "BLEND",
				["Bottom"] = 0.75,
				["Color"] = {
					["A"] = 1,
					["R"] = 1,
					["G"] = 1,
					["B"] = 1,
				},
				["Right"] = 0.73828125,
				["Left"] = 0.5,
				["Texture"] = "Interface\\Glues\\CharacterCreate\\UI-CharacterCreate-Classes",
			},
			["Default"] = {
				["Top"] = 0,
				["RAngle"] = 0,
				["Mode"] = "BLEND",
				["Bottom"] = 1,
				["Color"] = {
					["A"] = 1,
					["B"] = 1,
					["G"] = 1,
					["R"] = 1,
				},
				["Right"] = 1,
				["Left"] = 0,
				["Texture"] = "Interface\\TargetingFrame\\UI-StatusBar",
			},
			["PlayerClassIcon_DRUID"] = {
				["Top"] = 0,
				["RAngle"] = 0,
				["Mode"] = "BLEND",
				["Bottom"] = 0.25,
				["Color"] = {
					["A"] = 1,
					["R"] = 1,
					["G"] = 1,
					["B"] = 1,
				},
				["Right"] = 0.98828125,
				["Left"] = 0.7421875,
				["Texture"] = "Interface\\Glues\\CharacterCreate\\UI-CharacterCreate-Classes",
			},
			["PlayerClassIcon_WARLOCK"] = {
				["Top"] = 0.25,
				["RAngle"] = 0,
				["Mode"] = "BLEND",
				["Bottom"] = 0.5,
				["Color"] = {
					["A"] = 1,
					["R"] = 1,
					["G"] = 1,
					["B"] = 1,
				},
				["Right"] = 0.98828125,
				["Left"] = 0.7421875,
				["Texture"] = "Interface\\Glues\\CharacterCreate\\UI-CharacterCreate-Classes",
			},
			["RaidTarget4_GreenTriangle"] = {
				["Top"] = 0,
				["RAngle"] = 0,
				["Mode"] = "Blend",
				["Bottom"] = 0.25,
				["Color"] = {
					["A"] = 1,
					["R"] = 1,
					["G"] = 1,
					["B"] = 1,
				},
				["Right"] = 1,
				["Left"] = 0.75,
				["Texture"] = "Interface\\TargetingFrame\\UI-RaidTargetingIcons",
			},
		},
	}
end)